### ISSUE TITLE
Clipping artefacts

### ISSUE THREAD

**Issue by edwinRNDR** [lacuna/artifex#1]
While trying out the Artifex library I run into some clipping artefacts while finding difference and intersections of two circles. I think the problem is best explained by showing a video: https://www.youtube.com/watch?v=HfnP3vG0E-g

Code is a bit hard to share as I have linked Artifex code to a somewhat large codebase. Here is the integration code: https://github.com/openrndr/openrndr/commit/61b4962d58f36f07035d1c17a78dbc957ffe3257#diff-6d99a3e2c6edca20aea91f05e5079391

**Comment by ztellman** [comment]
Hi Edwin,

The video is showing up as "unavailable" for me.  If you could provide the exact control points for the regions you're operating on, that would be the most helpful for debugging purposes.

I honestly hadn't expected anyone to be using this yet, so there have been a few changes sitting on my machine the last few weeks.  I've pushed them, let me know if they happen to help with your issue.

Zach

**Comment by edwinRNDR** [comment]
Hi Zach,

I have updated the video URL at some point, maybe you were still seeing an older version of my post.

I have quickly tested your recently committed code, which seems to have resolved the problems I was seeing. I will expose it to some harder problems in the course of the following weeks to see how it holds up. 

Also, are you OK with me adopting/verbatim copying the Artifex codebase into the [OPENRNDR](https://github.com/openrndr/openrndr) codebase?

**Comment by ztellman** [comment]
Great, I appreciate you putting it through its paces, please let me know if you find any other problems.

The MIT license allows you to copy/paste the code into your project as long as you provide a reference to the original project, but in case it's easier I've just deployed `0.1.0-alpha1` of this project to Maven, which should be an easier way to use the library.
